
spring.application.name=recruitment-platform

spring.datasource.url=jdbc:postgresql://localhost:5432/recruitment_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.format-sql=true

server.port=8080

bezkoder.app.jwtSecret=MaCleSecreteJWTTrèsLongue1234567890
bezkoder.app.jwtExpirationMs=86400000

file.upload-dir=uploads
cors.allowed-origins=http://localhost:4200

spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=10MB
spring.servlet.multipart.file-size-threshold=2KB


file.max-size=5MB
file.allowed-types=application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document

spring.servlet.multipart.enabled=true

logging.level.org.springframework.security=DEBUG
logging.level.com.pfe.recrutement=DEBUG

spring.security.csrf.enabled=false

spring.mail.host=smtp.gmail.com
spring.mail.port=465
spring.mail.username=dhaouimanel05@gmail.com

spring.mail.password=wdcpmxgazjhkisvm
spring.mail.protocol=smtps
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.smtp.connectiontimeout=15000
spring.mail.properties.mail.smtp.timeout=15000
spring.mail.properties.mail.smtp.writetimeout=15000

spring.mail.properties.mail.smtp.ssl.checkserveridentity=false

recruitment.email.sender=dhaouimanel05@gmail.com
recruitment.email.sender.name=Plateforme de Recrutement


logging.level.com.pfe.recrutement.recruitment_platform.security.jwt=DEBUG

spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.model=phi3
spring.ai.ollama.embedding.model=nomic-embed-text


# Google OAuth
google.client.id=272144679807-bgrvahq0r3hpk7r2ek4cjv3qck4orlnr.apps.googleusercontent.com
google.client.secret=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
google.redirect.uri=http://localhost:4200/auth/google/callback

# LinkedIn OAuth
linkedin.client.id=XXXXX
linkedin.client.secret=XXXXX
linkedin.redirect.uri=http://localhost:4200/auth/linkedin/callback